import type { WorkspaceSummary } from "../types/workspace";

// Dev-only sample fleet. Shapes the orchestrator's Workers list and a worker's Git
// review rail so the workbench is legible before a daemon is attached.
export const mockWorkspaces: WorkspaceSummary[] = [
  {
    id: "agent-orchestrator",
    name: "reverbcode",
    path: "/Users/ashishhuddar/agent-orchestrator-1",
    type: "main",
    pullRequest: { number: 156, state: "open" },
    sessions: [
      {
        id: "fix-webgl-fallback",
        workspaceId: "agent-orchestrator",
        workspaceName: "reverbcode",
        title: "fix-webgl-fallback",
        provider: "claude-code",
        branch: "fix/webgl-fallback",
        status: "needs_input",
        displayStatus: "needs_you",
        updatedAt: "4m",
      },
      {
        id: "auth-token-rotation",
        workspaceId: "agent-orchestrator",
        workspaceName: "reverbcode",
        title: "auth-token-rotation",
        provider: "codex",
        branch: "fix/auth",
        status: "needs_input",
        displayStatus: "needs_you",
        updatedAt: "9m",
      },
    ],
  },
  {
    id: "api-gateway",
    name: "api-gateway",
    path: "/Users/ashishhuddar/api-gateway",
    type: "main",
    pullRequest: { number: 156, state: "open" },
    sessions: [
      {
        id: "refactor-mux",
        workspaceId: "api-gateway",
        workspaceName: "api-gateway",
        title: "refactor-mux",
        provider: "claude-code",
        branch: "refactor/mux",
        status: "running",
        displayStatus: "mergeable",
        updatedAt: "now",
        commitMessage: "mux: collapse dispatch to one goroutine",
        pullRequest: { number: 156, state: "open" },
        changedFiles: [
          { path: "internal/mux/terminal_mux.go", additions: 84, deletions: 12 },
          { path: "internal/cdc/broadcaster.go", additions: 31, deletions: 4 },
          { path: "internal/httpd/api.go", additions: 5, deletions: 2 },
          { path: "internal/mux/frame/frame.go", additions: 12, deletions: 0 },
        ],
      },
      {
        id: "bump-deps",
        workspaceId: "api-gateway",
        workspaceName: "api-gateway",
        title: "bump-deps",
        provider: "codex",
        branch: "chore/bump-deps",
        status: "running",
        displayStatus: "working",
        updatedAt: "1m",
      },
      {
        id: "flaky-e2e-retry",
        workspaceId: "api-gateway",
        workspaceName: "api-gateway",
        title: "flaky-e2e-retry",
        provider: "opencode",
        branch: "test/flaky-e2e",
        status: "stopped",
        displayStatus: "done",
        updatedAt: "1h",
      },
    ],
  },
];
