import type { WorkspaceSummary } from "../types/workspace";

const now = new Date().toISOString();
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export const mockWorkspaces: WorkspaceSummary[] = [
	{
		id: "api-gateway",
		name: "api-gateway",
		path: "/Users/me/api-gateway",
		sessions: [
			{
				id: "refactor-mux",
				terminalHandleId: "refactor-mux/terminal_0",
				workspaceId: "api-gateway",
				workspaceName: "api-gateway",
				title: "Split terminal mux responsibilities",
				provider: "claude-code",
				branch: "feat/refactor-mux",
				status: "working",
				updatedAt: now,
				createdAt: hoursAgo(4),
				changedFiles: [
					{
						path: "internal/mux/terminal_mux.go",
						additions: 42,
						deletions: 8,
					},
				],
				commitMessage: "refactor terminal mux",
			},
			{
				id: "fix-auth-timeouts",
				workspaceId: "api-gateway",
				workspaceName: "api-gateway",
				title: "fix auth timeout retry loop",
				provider: "codex",
				branch: "fix/auth-timeouts",
				status: "ci_failed",
				updatedAt: hoursAgo(1),
				createdAt: hoursAgo(6),
				pullRequest: { number: 184, state: "open" },
			},
			{
				id: "rate-limit-headers",
				workspaceId: "api-gateway",
				workspaceName: "api-gateway",
				title: "add rate limit headers",
				provider: "opencode",
				branch: "feat/rate-limit-headers",
				status: "review_pending",
				updatedAt: hoursAgo(2),
				createdAt: hoursAgo(9),
				pullRequest: { number: 185, state: "open" },
			},
		],
	},
	{
		id: "webgl-preview",
		name: "webgl-preview",
		path: "/Users/me/webgl-preview",
		sessions: [
			{
				id: "fix-webgl-fallback",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "Restore fallback renderer after WebGL init fails",
				provider: "codex",
				branch: "fix/webgl-fallback",
				status: "needs_input",
				updatedAt: now,
				createdAt: hoursAgo(4),
			},
			{
				id: "shader-cache",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "cache compiled shader programs",
				provider: "claude-code",
				branch: "feat/shader-cache",
				status: "working",
				updatedAt: hoursAgo(0.5),
				createdAt: hoursAgo(2),
				changedFiles: [
					{ path: "src/render/shader-cache.ts", additions: 86, deletions: 12 },
					{ path: "src/render/webgl-context.ts", additions: 24, deletions: 5 },
				],
			},
			{
				id: "texture-leak",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "stop texture leak on scene reload",
				provider: "codex",
				branch: "fix/texture-leak",
				status: "ci_failed",
				updatedAt: hoursAgo(1.5),
				createdAt: hoursAgo(7),
				pullRequest: { number: 51, state: "open" },
			},
			{
				id: "review-camera-pan",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "smooth camera pan controls",
				provider: "aider",
				branch: "feat/camera-pan",
				status: "review_pending",
				updatedAt: hoursAgo(3),
				createdAt: hoursAgo(10),
				pullRequest: { number: 52, state: "open" },
			},
			{
				id: "draft-webgpu-probe",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "probe WebGPU support before init",
				provider: "opencode",
				branch: "feat/webgpu-probe",
				status: "draft",
				updatedAt: hoursAgo(5),
				createdAt: hoursAgo(12),
				pullRequest: { number: 53, state: "draft" },
			},
			{
				id: "merge-frame-stats",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "ship frame statistics overlay",
				provider: "codex",
				branch: "feat/frame-stats",
				status: "mergeable",
				updatedAt: hoursAgo(0.25),
				createdAt: hoursAgo(14),
				pullRequest: { number: 54, state: "open" },
			},
			{
				id: "approved-pixel-ratio",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "respect device pixel ratio",
				provider: "claude-code",
				branch: "fix/device-pixel-ratio",
				status: "approved",
				updatedAt: hoursAgo(2.5),
				createdAt: hoursAgo(16),
				pullRequest: { number: 55, state: "open" },
			},
			{
				id: "input-pointer-lock",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "pointer lock escape handling",
				provider: "codex",
				branch: "fix/pointer-lock",
				status: "changes_requested",
				updatedAt: hoursAgo(4),
				createdAt: hoursAgo(18),
				pullRequest: { number: 56, state: "open" },
			},
		],
	},
	{
		id: "mobile-shell",
		name: "mobile-shell",
		path: "/Users/me/mobile-shell",
		sessions: [
			{
				id: "nav-gesture",
				workspaceId: "mobile-shell",
				workspaceName: "mobile-shell",
				title: "repair back swipe gesture",
				provider: "codex",
				branch: "fix/back-swipe",
				status: "working",
				updatedAt: hoursAgo(0.75),
				createdAt: hoursAgo(3),
			},
			{
				id: "profile-sheet",
				workspaceId: "mobile-shell",
				workspaceName: "mobile-shell",
				title: "profile sheet accessibility pass",
				provider: "claude-code",
				branch: "fix/profile-sheet-a11y",
				status: "mergeable",
				updatedAt: hoursAgo(1.25),
				createdAt: hoursAgo(8),
				pullRequest: { number: 92, state: "open" },
			},
		],
	},
	{
		id: "billing-portal",
		name: "billing-portal",
		path: "/Users/me/billing-portal",
		sessions: [
			{
				id: "invoice-export",
				workspaceId: "billing-portal",
				workspaceName: "billing-portal",
				title: "invoice CSV export",
				provider: "opencode",
				branch: "feat/invoice-export",
				status: "review_pending",
				updatedAt: hoursAgo(2.25),
				createdAt: hoursAgo(11),
				pullRequest: { number: 117, state: "open" },
			},
			{
				id: "tax-id-validation",
				workspaceId: "billing-portal",
				workspaceName: "billing-portal",
				title: "tax id validation errors",
				provider: "codex",
				branch: "fix/tax-id-validation",
				status: "needs_input",
				updatedAt: hoursAgo(1.75),
				createdAt: hoursAgo(5),
			},
		],
	},
];
