import type { WorkspaceSummary } from "../types/workspace";

export const mockWorkspaces: WorkspaceSummary[] = [
	{
		id: "api-gateway",
		name: "api-gateway",
		path: "/Users/me/api-gateway",
		sessions: [
			{
				id: "refactor-mux",
				terminalHandleId: "refactor-mux/terminal_0",
				workspaceId: "api-gateway",
				workspaceName: "api-gateway",
				title: "refactor-mux",
				provider: "claude-code",
				branch: "feat/refactor-mux",
				status: "working",
				updatedAt: new Date().toISOString(),
				createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
				changedFiles: [
					{
						path: "internal/mux/terminal_mux.go",
						additions: 42,
						deletions: 8,
					},
				],
				commitMessage: "refactor terminal mux",
				prs: [],
			},
			{
				id: "stacked-auth",
				terminalHandleId: "stacked-auth/terminal_0",
				workspaceId: "api-gateway",
				workspaceName: "api-gateway",
				title: "auth stack",
				provider: "claude-code",
				branch: "feat/ns",
				status: "review_pending",
				updatedAt: new Date().toISOString(),
				createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
				// One session owning a stack: open root, draft child, merged base.
				prs: [
					{
						url: "https://github.com/me/api-gateway/pull/41",
						number: 41,
						state: "open",
						ci: "passing",
						review: "approved",
						mergeability: "mergeable",
						reviewComments: false,
						updatedAt: new Date().toISOString(),
					},
					{
						url: "https://github.com/me/api-gateway/pull/42",
						number: 42,
						state: "draft",
						ci: "pending",
						review: "none",
						mergeability: "unknown",
						reviewComments: false,
						updatedAt: new Date().toISOString(),
					},
					{
						url: "https://github.com/me/api-gateway/pull/40",
						number: 40,
						state: "merged",
						ci: "passing",
						review: "approved",
						mergeability: "mergeable",
						reviewComments: false,
						updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
					},
				],
			},
		],
	},
	{
		id: "webgl-preview",
		name: "webgl-preview",
		path: "/Users/me/webgl-preview",
		sessions: [
			{
				id: "fix-webgl-fallback",
				workspaceId: "webgl-preview",
				workspaceName: "webgl-preview",
				title: "fix-webgl-fallback",
				provider: "codex",
				branch: "fix/webgl-fallback",
				status: "needs_input",
				updatedAt: new Date().toISOString(),
				createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
				prs: [],
			},
		],
	},
];
